# Site settings
title: Widya Puspitaloka
email: widyapuspitaloka@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Widya Puspitaloka.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://widyapuspitaloka.github.io" # the base hostname & protocol for your site
twitter_username: WidyaAyuPuspita
github_username:  WidyaPuspitaloka

# Build settings
markdown: kramdown
